//  Copyright (c) 2012-2014 Jakub Filipowicz <jakubf@gmail.com>
//
//  This program is free software; you can redistribute it and/or modify
//  it under the terms of the GNU General Public License as published by
//  the Free Software Foundation; either version 2 of the License, or
//  (at your option) any later version.
//
//  This program is distributed in the hope that it will be useful,
//  but WITHOUT ANY WARRANTY; without even the implied warranty of
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//  GNU General Public License for more details.
//
//  You should have received a copy of the GNU General Public License
//  along with this program; if not, write to the Free Software
//  Foundation, Inc.,
//  51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA

#include <stdlib.h>

#include "emdas.h"
#include "iset.h"

static const struct opdef * get_extop_37(uint16_t opcode);
static const struct opdef * get_extop_70(uint16_t opcode);
static const struct opdef * get_extop_71(uint16_t opcode);
static const struct opdef * get_extop_72(uint16_t opcode);
static const struct opdef * get_extop_73(uint16_t opcode);
static const struct opdef * get_extop_74(uint16_t opcode);
static const struct opdef * get_extop_75(uint16_t opcode);
static const struct opdef * get_extop_76(uint16_t opcode);
static const struct opdef * get_extop_77(uint16_t opcode);

static const struct opdef iset[] = {
	{ 000, OP_NONE, OP_GR_NONE, NULL, ARG_UNKNOWN, OP_FL_NONE },
	{ 001, OP_NONE, OP_GR_NONE, NULL, ARG_UNKNOWN, OP_FL_NONE },
	{ 002, OP_NONE, OP_GR_NONE, NULL, ARG_UNKNOWN, OP_FL_NONE },
	{ 003, OP_NONE, OP_GR_NONE, NULL, ARG_UNKNOWN, OP_FL_NONE },
	{ 004, OP_NONE, OP_GR_NONE, NULL, ARG_UNKNOWN, OP_FL_NONE },
	{ 005, OP_NONE, OP_GR_NONE, NULL, ARG_UNKNOWN, OP_FL_NONE },
	{ 006, OP_NONE, OP_GR_NONE, NULL, ARG_UNKNOWN, OP_FL_NONE },
	{ 007, OP_NONE, OP_GR_NONE, NULL, ARG_UNKNOWN, OP_FL_NONE },
	{ 010, OP_NONE, OP_GR_NONE, NULL, ARG_UNKNOWN, OP_FL_NONE },
	{ 011, OP_NONE, OP_GR_NONE, NULL, ARG_UNKNOWN, OP_FL_NONE },
	{ 012, OP_NONE, OP_GR_NONE, NULL, ARG_UNKNOWN, OP_FL_NONE },
	{ 013, OP_NONE, OP_GR_NONE, NULL, ARG_UNKNOWN, OP_FL_NONE },
	{ 014, OP_NONE, OP_GR_NONE, NULL, ARG_UNKNOWN, OP_FL_NONE },
	{ 015, OP_NONE, OP_GR_NONE, NULL, ARG_UNKNOWN, OP_FL_NONE },
	{ 016, OP_NONE, OP_GR_NONE, NULL, ARG_UNKNOWN, OP_FL_NONE },
	{ 017, OP_NONE, OP_GR_NONE, NULL, ARG_UNKNOWN, OP_FL_NONE },
	
	{ 020, OP_LW, OP_GR_NORM, NULL, ARG_REG | ARG_NORM, OP_FL_NONE },
	{ 021, OP_TW, OP_GR_NORM, NULL, ARG_REG | ARG_NORM | ARG_A_WORD, OP_FL_NONE },
	{ 022, OP_LS, OP_GR_NORM, NULL, ARG_REG | ARG_NORM, OP_FL_NONE },
	{ 023, OP_RI, OP_GR_NORM, NULL, ARG_REG | ARG_NORM | ARG_REGIND, OP_FL_NONE },
	{ 024, OP_RW, OP_GR_NORM, NULL, ARG_REG | ARG_NORM | ARG_A_WORD, OP_FL_NONE },
	{ 025, OP_PW, OP_GR_NORM, NULL, ARG_REG | ARG_NORM | ARG_A_WORD, OP_FL_NONE },
	{ 026, OP_RJ, OP_GR_NORM, NULL, ARG_REG | ARG_NORM | ARG_A_JUMP, OP_FL_NONE },
	{ 027, OP_IS, OP_GR_NORM, NULL, ARG_REG | ARG_NORM | ARG_A_JUMP, OP_FL_NONE },
	{ 030, OP_BB, OP_GR_NORM, NULL, ARG_REG | ARG_NORM, OP_FL_NONE },
	{ 031, OP_BM, OP_GR_NORM, NULL, ARG_REG | ARG_NORM | ARG_A_JUMP, OP_FL_NONE },
	{ 032, OP_BS, OP_GR_NORM, NULL, ARG_REG | ARG_NORM, OP_FL_NONE },
	{ 033, OP_BC, OP_GR_NORM, NULL, ARG_REG | ARG_NORM, OP_FL_NONE },
	{ 034, OP_BN, OP_GR_NORM, NULL, ARG_REG | ARG_NORM, OP_FL_NONE },
	{ 035, OP_OU, OP_GR_NORM, NULL, ARG_REG | ARG_NORM, OP_FL_OS | OP_FL_IO },
	{ 036, OP_IN, OP_GR_NORM, NULL, ARG_REG | ARG_NORM, OP_FL_OS | OP_FL_IO },

	{ 037, OP_NONE, OP_GR_NONE, get_extop_37, ARG_UNKNOWN, OP_FL_NONE },

	{ 040, OP_AW, OP_GR_NORM, NULL, ARG_REG | ARG_NORM, OP_FL_NONE },
	{ 041, OP_AC, OP_GR_NORM, NULL, ARG_REG | ARG_NORM, OP_FL_NONE },
	{ 042, OP_SW, OP_GR_NORM, NULL, ARG_REG | ARG_NORM, OP_FL_NONE },
	{ 043, OP_CW, OP_GR_NORM, NULL, ARG_REG | ARG_NORM, OP_FL_NONE },
	{ 044, OP_OR, OP_GR_NORM, NULL, ARG_REG | ARG_NORM, OP_FL_NONE },
	{ 045, OP_OM, OP_GR_NORM, NULL, ARG_REG | ARG_NORM | ARG_A_WORD, OP_FL_NONE },
	{ 046, OP_NR, OP_GR_NORM, NULL, ARG_REG | ARG_NORM, OP_FL_NONE },
	{ 047, OP_NM, OP_GR_NORM, NULL, ARG_REG | ARG_NORM | ARG_A_WORD, OP_FL_NONE },
	{ 050, OP_ER, OP_GR_NORM, NULL, ARG_REG | ARG_NORM, OP_FL_NONE },
	{ 051, OP_EM, OP_GR_NORM, NULL, ARG_REG | ARG_NORM | ARG_A_WORD, OP_FL_NONE },
	{ 052, OP_XR, OP_GR_NORM, NULL, ARG_REG | ARG_NORM, OP_FL_NONE },
	{ 053, OP_XM, OP_GR_NORM, NULL, ARG_REG | ARG_NORM | ARG_A_WORD, OP_FL_NONE },
	{ 054, OP_CL, OP_GR_NORM, NULL, ARG_REG | ARG_NORM, OP_FL_NONE },
	{ 055, OP_LB, OP_GR_NORM, NULL, ARG_REG | ARG_NORM | ARG_A_BYTE, OP_FL_NONE },
	{ 056, OP_RB, OP_GR_NORM, NULL, ARG_REG | ARG_NORM | ARG_A_BYTE, OP_FL_NONE },
	{ 057, OP_CB, OP_GR_NORM, NULL, ARG_REG | ARG_NORM | ARG_A_BYTE, OP_FL_NONE },

	{ 060, OP_AWT, OP_GR_KA1, NULL, ARG_REG | ARG_SHORT7, OP_FL_NONE },
	{ 061, OP_TRB, OP_GR_KA1, NULL, ARG_REG | ARG_SHORT7, OP_FL_NONE },
	{ 062, OP_IRB, OP_GR_KA1, NULL, ARG_REG | ARG_SHORT7 | ARG_RELATIVE | ARG_A_JUMP, OP_FL_NONE },
	{ 063, OP_DRB, OP_GR_KA1, NULL, ARG_REG | ARG_SHORT7 | ARG_RELATIVE | ARG_A_JUMP, OP_FL_NONE },
	{ 064, OP_CWT, OP_GR_KA1, NULL, ARG_REG | ARG_SHORT7, OP_FL_NONE },
	{ 065, OP_LWT, OP_GR_KA1, NULL, ARG_REG | ARG_SHORT7, OP_FL_NONE },
	{ 066, OP_LWS, OP_GR_KA1, NULL, ARG_REG | ARG_SHORT7 | ARG_RELATIVE | ARG_A_WORD, OP_FL_NONE },
	{ 067, OP_RWS, OP_GR_KA1, NULL, ARG_REG | ARG_SHORT7 | ARG_RELATIVE | ARG_A_WORD, OP_FL_NONE },

	{ 070, OP_NONE, OP_GR_NONE, get_extop_70, ARG_UNKNOWN, OP_FL_NONE },
	{ 071, OP_NONE, OP_GR_NONE, get_extop_71, ARG_UNKNOWN, OP_FL_NONE },
	{ 072, OP_NONE, OP_GR_NONE, get_extop_72, ARG_UNKNOWN, OP_FL_NONE },
	{ 073, OP_NONE, OP_GR_NONE, get_extop_73, ARG_UNKNOWN, OP_FL_NONE },
	{ 074, OP_NONE, OP_GR_NONE, get_extop_74, ARG_UNKNOWN, OP_FL_NONE },
	{ 075, OP_NONE, OP_GR_NONE, get_extop_75, ARG_UNKNOWN, OP_FL_NONE },
	{ 076, OP_NONE, OP_GR_NONE, get_extop_76, ARG_UNKNOWN, OP_FL_NONE },
	{ 077, OP_NONE, OP_GR_NONE, get_extop_77, ARG_UNKNOWN, OP_FL_NONE }
};

static const struct opdef iset_37[] = {
	{ 0, OP_AD, OP_GR_FD, NULL, ARG_NORM | ARG_A_DWORD, OP_FL_NONE },
	{ 1, OP_SD, OP_GR_FD, NULL, ARG_NORM | ARG_A_DWORD, OP_FL_NONE },
	{ 2, OP_MW, OP_GR_FD, NULL, ARG_NORM | ARG_A_DWORD, OP_FL_NONE },
	{ 3, OP_DW, OP_GR_FD, NULL, ARG_NORM | ARG_A_DWORD, OP_FL_NONE },
	{ 4, OP_AF, OP_GR_FD, NULL, ARG_NORM | ARG_A_FLOAT, OP_FL_NONE },
	{ 5, OP_SF, OP_GR_FD, NULL, ARG_NORM | ARG_A_FLOAT, OP_FL_NONE },
	{ 6, OP_MF, OP_GR_FD, NULL, ARG_NORM | ARG_A_FLOAT, OP_FL_NONE },
	{ 7, OP_DF, OP_GR_FD, NULL, ARG_NORM | ARG_A_FLOAT, OP_FL_NONE }
};

static const struct opdef iset_70[] = {
	{ 0, OP_UJS, OP_GR_JS, NULL, ARG_SHORT7 | ARG_RELATIVE | ARG_A_JUMP, OP_FL_NONE },
	{ 1, OP_JLS, OP_GR_JS, NULL, ARG_SHORT7 | ARG_RELATIVE | ARG_A_JUMP, OP_FL_NONE },
	{ 2, OP_JES, OP_GR_JS, NULL, ARG_SHORT7 | ARG_RELATIVE | ARG_A_JUMP, OP_FL_NONE },
	{ 3, OP_JGS, OP_GR_JS, NULL, ARG_SHORT7 | ARG_RELATIVE | ARG_A_JUMP, OP_FL_NONE },
	{ 4, OP_JVS, OP_GR_JS, NULL, ARG_SHORT7 | ARG_RELATIVE | ARG_A_JUMP, OP_FL_NONE },
	{ 5, OP_JXS, OP_GR_JS, NULL, ARG_SHORT7 | ARG_RELATIVE | ARG_A_JUMP, OP_FL_NONE },
	{ 6, OP_JYS, OP_GR_JS, NULL, ARG_SHORT7 | ARG_RELATIVE | ARG_A_JUMP, OP_FL_NONE },
	{ 7, OP_JCS, OP_GR_JS, NULL, ARG_SHORT7 | ARG_RELATIVE | ARG_A_JUMP, OP_FL_NONE }
};

static const struct opdef iset_71[] = {
	{ 0, OP_BLC, OP_GR_KA2, NULL, ARG_SHORT8, OP_FL_NONE },
	{ 1, OP_EXL, OP_GR_KA2, NULL, ARG_SHORT8, OP_FL_NONE },
	{ 2, OP_BRC, OP_GR_KA2, NULL, ARG_SHORT8, OP_FL_NONE },
	{ 3, OP_NRF, OP_GR_KA2, NULL, ARG_SHORT8, OP_FL_NONE }
};

static const struct opdef iset_72[] = {
	{ 0000, OP_RIC, OP_GR_C, NULL, ARG_REG, OP_FL_NONE },
	{ 0001, OP_ZLB, OP_GR_C, NULL, ARG_REG, OP_FL_NONE },
	{ 0002, OP_SXU, OP_GR_C, NULL, ARG_REG, OP_FL_NONE },
	{ 0003, OP_NGA, OP_GR_C, NULL, ARG_REG, OP_FL_NONE },
	{ 0004, OP_SLZ, OP_GR_C, NULL, ARG_REG, OP_FL_NONE },
	{ 0005, OP_SLY, OP_GR_C, NULL, ARG_REG, OP_FL_NONE },
	{ 0006, OP_SLX, OP_GR_C, NULL, ARG_REG, OP_FL_NONE },
	{ 0007, OP_SRY, OP_GR_C, NULL, ARG_REG, OP_FL_NONE },
	{ 0010, OP_NGL, OP_GR_C, NULL, ARG_REG, OP_FL_NONE },
	{ 0011, OP_RPC, OP_GR_C, NULL, ARG_REG, OP_FL_NONE },
	{ 0012, OP_NONE, OP_GR_NONE, NULL, ARG_UNKNOWN, OP_FL_NONE },
	{ 0013, OP_NONE, OP_GR_NONE, NULL, ARG_UNKNOWN, OP_FL_NONE },
	{ 0014, OP_NONE, OP_GR_NONE, NULL, ARG_UNKNOWN, OP_FL_NONE },
	{ 0015, OP_NONE, OP_GR_NONE, NULL, ARG_UNKNOWN, OP_FL_NONE },
	{ 0016, OP_NONE, OP_GR_NONE, NULL, ARG_UNKNOWN, OP_FL_NONE },
	{ 0017, OP_NONE, OP_GR_NONE, NULL, ARG_UNKNOWN, OP_FL_NONE },
	{ 0020, OP_SHC, OP_GR_C, NULL, ARG_REG | ARG_SHORT4, OP_FL_NONE },
	{ 0021, OP_SHC, OP_GR_C, NULL, ARG_REG | ARG_SHORT4, OP_FL_NONE },
	{ 0022, OP_SHC, OP_GR_C, NULL, ARG_REG | ARG_SHORT4, OP_FL_NONE },
	{ 0023, OP_SHC, OP_GR_C, NULL, ARG_REG | ARG_SHORT4, OP_FL_NONE },
	{ 0024, OP_SHC, OP_GR_C, NULL, ARG_REG | ARG_SHORT4, OP_FL_NONE },
	{ 0025, OP_SHC, OP_GR_C, NULL, ARG_REG | ARG_SHORT4, OP_FL_NONE },
	{ 0026, OP_SHC, OP_GR_C, NULL, ARG_REG | ARG_SHORT4, OP_FL_NONE },
	{ 0027, OP_SHC, OP_GR_C, NULL, ARG_REG | ARG_SHORT4, OP_FL_NONE },
	{ 0030, OP_NONE, OP_GR_NONE, NULL, ARG_UNKNOWN, OP_FL_NONE },
	{ 0031, OP_NONE, OP_GR_NONE, NULL, ARG_UNKNOWN, OP_FL_NONE },
	{ 0032, OP_NONE, OP_GR_NONE, NULL, ARG_UNKNOWN, OP_FL_NONE },
	{ 0033, OP_NONE, OP_GR_NONE, NULL, ARG_UNKNOWN, OP_FL_NONE },
	{ 0034, OP_NONE, OP_GR_NONE, NULL, ARG_UNKNOWN, OP_FL_NONE },
	{ 0035, OP_NONE, OP_GR_NONE, NULL, ARG_UNKNOWN, OP_FL_NONE },
	{ 0036, OP_NONE, OP_GR_NONE, NULL, ARG_UNKNOWN, OP_FL_NONE },
	{ 0037, OP_NONE, OP_GR_NONE, NULL, ARG_UNKNOWN, OP_FL_NONE },
	{ 0040, OP_NONE, OP_GR_NONE, NULL, ARG_UNKNOWN, OP_FL_NONE },
	{ 0041, OP_NONE, OP_GR_NONE, NULL, ARG_UNKNOWN, OP_FL_NONE },
	{ 0042, OP_NONE, OP_GR_NONE, NULL, ARG_UNKNOWN, OP_FL_NONE },
	{ 0043, OP_NONE, OP_GR_NONE, NULL, ARG_UNKNOWN, OP_FL_NONE },
	{ 0044, OP_NONE, OP_GR_NONE, NULL, ARG_UNKNOWN, OP_FL_NONE },
	{ 0045, OP_NONE, OP_GR_NONE, NULL, ARG_UNKNOWN, OP_FL_NONE },
	{ 0046, OP_NONE, OP_GR_NONE, NULL, ARG_UNKNOWN, OP_FL_NONE },
	{ 0047, OP_NONE, OP_GR_NONE, NULL, ARG_UNKNOWN, OP_FL_NONE },
	{ 0050, OP_NONE, OP_GR_NONE, NULL, ARG_UNKNOWN, OP_FL_NONE },
	{ 0051, OP_NONE, OP_GR_NONE, NULL, ARG_UNKNOWN, OP_FL_NONE },
	{ 0052, OP_NONE, OP_GR_NONE, NULL, ARG_UNKNOWN, OP_FL_NONE },
	{ 0053, OP_NONE, OP_GR_NONE, NULL, ARG_UNKNOWN, OP_FL_NONE },
	{ 0054, OP_NONE, OP_GR_NONE, NULL, ARG_UNKNOWN, OP_FL_NONE },
	{ 0055, OP_NONE, OP_GR_NONE, NULL, ARG_UNKNOWN, OP_FL_NONE },
	{ 0056, OP_NONE, OP_GR_NONE, NULL, ARG_UNKNOWN, OP_FL_NONE },
	{ 0057, OP_NONE, OP_GR_NONE, NULL, ARG_UNKNOWN, OP_FL_NONE },
	{ 0060, OP_NONE, OP_GR_NONE, NULL, ARG_UNKNOWN, OP_FL_NONE },
	{ 0061, OP_NONE, OP_GR_NONE, NULL, ARG_UNKNOWN, OP_FL_NONE },
	{ 0062, OP_NONE, OP_GR_NONE, NULL, ARG_UNKNOWN, OP_FL_NONE },
	{ 0063, OP_NONE, OP_GR_NONE, NULL, ARG_UNKNOWN, OP_FL_NONE },
	{ 0064, OP_NONE, OP_GR_NONE, NULL, ARG_UNKNOWN, OP_FL_NONE },
	{ 0065, OP_NONE, OP_GR_NONE, NULL, ARG_UNKNOWN, OP_FL_NONE },
	{ 0066, OP_NONE, OP_GR_NONE, NULL, ARG_UNKNOWN, OP_FL_NONE },
	{ 0067, OP_NONE, OP_GR_NONE, NULL, ARG_UNKNOWN, OP_FL_NONE },
	{ 0070, OP_NONE, OP_GR_NONE, NULL, ARG_UNKNOWN, OP_FL_NONE },
	{ 0071, OP_NONE, OP_GR_NONE, NULL, ARG_UNKNOWN, OP_FL_NONE },
	{ 0072, OP_NONE, OP_GR_NONE, NULL, ARG_UNKNOWN, OP_FL_NONE },
	{ 0073, OP_NONE, OP_GR_NONE, NULL, ARG_UNKNOWN, OP_FL_NONE },
	{ 0074, OP_NONE, OP_GR_NONE, NULL, ARG_UNKNOWN, OP_FL_NONE },
	{ 0075, OP_NONE, OP_GR_NONE, NULL, ARG_UNKNOWN, OP_FL_NONE },
	{ 0076, OP_NONE, OP_GR_NONE, NULL, ARG_UNKNOWN, OP_FL_NONE },
	{ 0077, OP_NONE, OP_GR_NONE, NULL, ARG_UNKNOWN, OP_FL_NONE },
	{ 0100, OP_RKY, OP_GR_C, NULL, ARG_REG, OP_FL_NONE },
	{ 0101, OP_ZRB, OP_GR_C, NULL, ARG_REG, OP_FL_NONE },
	{ 0102, OP_SXL, OP_GR_C, NULL, ARG_REG, OP_FL_NONE },
	{ 0103, OP_NGC, OP_GR_C, NULL, ARG_REG, OP_FL_NONE },
	{ 0104, OP_SVZ, OP_GR_C, NULL, ARG_REG, OP_FL_NONE },
	{ 0105, OP_SVY, OP_GR_C, NULL, ARG_REG, OP_FL_NONE },
	{ 0106, OP_SVX, OP_GR_C, NULL, ARG_REG, OP_FL_NONE },
	{ 0107, OP_SRX, OP_GR_C, NULL, ARG_REG, OP_FL_NONE },
	{ 0110, OP_SRZ, OP_GR_C, NULL, ARG_REG, OP_FL_NONE },
	{ 0111, OP_LPC, OP_GR_C, NULL, ARG_REG, OP_FL_NONE },
	{ 0112, OP_NONE, OP_GR_NONE, NULL, ARG_UNKNOWN, OP_FL_NONE },
	{ 0113, OP_NONE, OP_GR_NONE, NULL, ARG_UNKNOWN, OP_FL_NONE },
	{ 0114, OP_NONE, OP_GR_NONE, NULL, ARG_UNKNOWN, OP_FL_NONE },
	{ 0115, OP_NONE, OP_GR_NONE, NULL, ARG_UNKNOWN, OP_FL_NONE },
	{ 0116, OP_NONE, OP_GR_NONE, NULL, ARG_UNKNOWN, OP_FL_NONE },
	{ 0117, OP_NONE, OP_GR_NONE, NULL, ARG_UNKNOWN, OP_FL_NONE },
	{ 0121, OP_SHC, OP_GR_C, NULL, ARG_REG | ARG_SHORT4, OP_FL_NONE },
	{ 0120, OP_SHC, OP_GR_C, NULL, ARG_REG | ARG_SHORT4, OP_FL_NONE },
	{ 0122, OP_SHC, OP_GR_C, NULL, ARG_REG | ARG_SHORT4, OP_FL_NONE },
	{ 0123, OP_SHC, OP_GR_C, NULL, ARG_REG | ARG_SHORT4, OP_FL_NONE },
	{ 0124, OP_SHC, OP_GR_C, NULL, ARG_REG | ARG_SHORT4, OP_FL_NONE },
	{ 0125, OP_SHC, OP_GR_C, NULL, ARG_REG | ARG_SHORT4, OP_FL_NONE },
	{ 0126, OP_SHC, OP_GR_C, NULL, ARG_REG | ARG_SHORT4, OP_FL_NONE },
	{ 0127, OP_SHC, OP_GR_C, NULL, ARG_REG | ARG_SHORT4, OP_FL_NONE },
	{ 0130, OP_NONE, OP_GR_NONE, NULL, ARG_UNKNOWN, OP_FL_NONE },
	{ 0131, OP_NONE, OP_GR_NONE, NULL, ARG_UNKNOWN, OP_FL_NONE },
	{ 0132, OP_NONE, OP_GR_NONE, NULL, ARG_UNKNOWN, OP_FL_NONE },
	{ 0133, OP_NONE, OP_GR_NONE, NULL, ARG_UNKNOWN, OP_FL_NONE },
	{ 0134, OP_NONE, OP_GR_NONE, NULL, ARG_UNKNOWN, OP_FL_NONE },
	{ 0135, OP_NONE, OP_GR_NONE, NULL, ARG_UNKNOWN, OP_FL_NONE },
	{ 0136, OP_NONE, OP_GR_NONE, NULL, ARG_UNKNOWN, OP_FL_NONE },
	{ 0137, OP_NONE, OP_GR_NONE, NULL, ARG_UNKNOWN, OP_FL_NONE },
	{ 0140, OP_NONE, OP_GR_NONE, NULL, ARG_UNKNOWN, OP_FL_NONE },
	{ 0141, OP_NONE, OP_GR_NONE, NULL, ARG_UNKNOWN, OP_FL_NONE },
	{ 0142, OP_NONE, OP_GR_NONE, NULL, ARG_UNKNOWN, OP_FL_NONE },
	{ 0143, OP_NONE, OP_GR_NONE, NULL, ARG_UNKNOWN, OP_FL_NONE },
	{ 0144, OP_NONE, OP_GR_NONE, NULL, ARG_UNKNOWN, OP_FL_NONE },
	{ 0145, OP_NONE, OP_GR_NONE, NULL, ARG_UNKNOWN, OP_FL_NONE },
	{ 0146, OP_NONE, OP_GR_NONE, NULL, ARG_UNKNOWN, OP_FL_NONE },
	{ 0147, OP_NONE, OP_GR_NONE, NULL, ARG_UNKNOWN, OP_FL_NONE },
	{ 0150, OP_NONE, OP_GR_NONE, NULL, ARG_UNKNOWN, OP_FL_NONE },
	{ 0151, OP_NONE, OP_GR_NONE, NULL, ARG_UNKNOWN, OP_FL_NONE },
	{ 0152, OP_NONE, OP_GR_NONE, NULL, ARG_UNKNOWN, OP_FL_NONE },
	{ 0153, OP_NONE, OP_GR_NONE, NULL, ARG_UNKNOWN, OP_FL_NONE },
	{ 0154, OP_NONE, OP_GR_NONE, NULL, ARG_UNKNOWN, OP_FL_NONE },
	{ 0155, OP_NONE, OP_GR_NONE, NULL, ARG_UNKNOWN, OP_FL_NONE },
	{ 0156, OP_NONE, OP_GR_NONE, NULL, ARG_UNKNOWN, OP_FL_NONE },
	{ 0157, OP_NONE, OP_GR_NONE, NULL, ARG_UNKNOWN, OP_FL_NONE },
	{ 0161, OP_NONE, OP_GR_NONE, NULL, ARG_UNKNOWN, OP_FL_NONE },
	{ 0160, OP_NONE, OP_GR_NONE, NULL, ARG_UNKNOWN, OP_FL_NONE },
	{ 0162, OP_NONE, OP_GR_NONE, NULL, ARG_UNKNOWN, OP_FL_NONE },
	{ 0163, OP_NONE, OP_GR_NONE, NULL, ARG_UNKNOWN, OP_FL_NONE },
	{ 0164, OP_NONE, OP_GR_NONE, NULL, ARG_UNKNOWN, OP_FL_NONE },
	{ 0165, OP_NONE, OP_GR_NONE, NULL, ARG_UNKNOWN, OP_FL_NONE },
	{ 0166, OP_NONE, OP_GR_NONE, NULL, ARG_UNKNOWN, OP_FL_NONE },
	{ 0167, OP_NONE, OP_GR_NONE, NULL, ARG_UNKNOWN, OP_FL_NONE },
	{ 0170, OP_NONE, OP_GR_NONE, NULL, ARG_UNKNOWN, OP_FL_NONE },
	{ 0171, OP_NONE, OP_GR_NONE, NULL, ARG_UNKNOWN, OP_FL_NONE },
	{ 0172, OP_NONE, OP_GR_NONE, NULL, ARG_UNKNOWN, OP_FL_NONE },
	{ 0173, OP_NONE, OP_GR_NONE, NULL, ARG_UNKNOWN, OP_FL_NONE },
	{ 0174, OP_NONE, OP_GR_NONE, NULL, ARG_UNKNOWN, OP_FL_NONE },
	{ 0175, OP_NONE, OP_GR_NONE, NULL, ARG_UNKNOWN, OP_FL_NONE },
	{ 0176, OP_NONE, OP_GR_NONE, NULL, ARG_UNKNOWN, OP_FL_NONE },
	{ 0177, OP_NONE, OP_GR_NONE, NULL, ARG_UNKNOWN, OP_FL_NONE }
};

static const struct opdef iset_73[] = {
	{ 0000, OP_HLT, OP_GR_S, NULL, ARG_SHORT7, OP_FL_OS },
	{ 0001, OP_HLT, OP_GR_S, NULL, ARG_SHORT7, OP_FL_OS },
	{ 0002, OP_HLT, OP_GR_S, NULL, ARG_SHORT7, OP_FL_OS },
	{ 0003, OP_HLT, OP_GR_S, NULL, ARG_SHORT7, OP_FL_OS },
	{ 0004, OP_HLT, OP_GR_S, NULL, ARG_SHORT7, OP_FL_OS },
	{ 0005, OP_HLT, OP_GR_S, NULL, ARG_SHORT7, OP_FL_OS },
	{ 0006, OP_HLT, OP_GR_S, NULL, ARG_SHORT7, OP_FL_OS },
	{ 0007, OP_HLT, OP_GR_S, NULL, ARG_SHORT7, OP_FL_OS },

	{ 0010, OP_MCL, OP_GR_S, NULL, ARG_NONE, OP_FL_OS },
	{ 0011, OP_MCL, OP_GR_S, NULL, ARG_NONE, OP_FL_OS },
	{ 0012, OP_MCL, OP_GR_S, NULL, ARG_NONE, OP_FL_OS },
	{ 0013, OP_MCL, OP_GR_S, NULL, ARG_NONE, OP_FL_OS },
	{ 0014, OP_MCL, OP_GR_S, NULL, ARG_NONE, OP_FL_OS },
	{ 0015, OP_MCL, OP_GR_S, NULL, ARG_NONE, OP_FL_OS },
	{ 0016, OP_MCL, OP_GR_S, NULL, ARG_NONE, OP_FL_OS },
	{ 0017, OP_MCL, OP_GR_S, NULL, ARG_NONE, OP_FL_OS },

	{ 0020, OP_CIT, OP_GR_S, NULL, ARG_NONE, OP_FL_OS },
	{ 0021, OP_SIL, OP_GR_S, NULL, ARG_NONE, OP_FL_OS },
	{ 0022, OP_SIU, OP_GR_S, NULL, ARG_NONE, OP_FL_OS },
	{ 0023, OP_SIT, OP_GR_S, NULL, ARG_NONE, OP_FL_OS },
	{ 0024, OP_SINT, OP_GR_S, NULL, ARG_NONE, OP_FL_OS | OP_FL_MX16 },
	{ 0025, OP_NONE, OP_GR_NONE, NULL, ARG_UNKNOWN, OP_FL_NONE },
	{ 0026, OP_NONE, OP_GR_NONE, NULL, ARG_UNKNOWN, OP_FL_NONE },
	{ 0027, OP_NONE, OP_GR_NONE, NULL, ARG_UNKNOWN, OP_FL_NONE },

	{ 0030, OP_GIU, OP_GR_S, NULL, ARG_NONE, OP_FL_OS },
	{ 0031, OP_GIU, OP_GR_S, NULL, ARG_NONE, OP_FL_OS },
	{ 0032, OP_GIU, OP_GR_S, NULL, ARG_NONE, OP_FL_OS },
	{ 0033, OP_GIU, OP_GR_S, NULL, ARG_NONE, OP_FL_OS },
	{ 0034, OP_GIU, OP_GR_S, NULL, ARG_NONE, OP_FL_OS },
	{ 0035, OP_GIU, OP_GR_S, NULL, ARG_NONE, OP_FL_OS },
	{ 0036, OP_GIU, OP_GR_S, NULL, ARG_NONE, OP_FL_OS },
	{ 0037, OP_GIU, OP_GR_S, NULL, ARG_NONE, OP_FL_OS },

	{ 0040, OP_LIP, OP_GR_S, NULL, ARG_NONE, OP_FL_OS },
	{ 0041, OP_LIP, OP_GR_S, NULL, ARG_NONE, OP_FL_OS },
	{ 0042, OP_LIP, OP_GR_S, NULL, ARG_NONE, OP_FL_OS },
	{ 0043, OP_LIP, OP_GR_S, NULL, ARG_NONE, OP_FL_OS },
	{ 0044, OP_LIP, OP_GR_S, NULL, ARG_NONE, OP_FL_OS },
	{ 0045, OP_LIP, OP_GR_S, NULL, ARG_NONE, OP_FL_OS },
	{ 0046, OP_LIP, OP_GR_S, NULL, ARG_NONE, OP_FL_OS },
	{ 0047, OP_LIP, OP_GR_S, NULL, ARG_NONE, OP_FL_OS },

	{ 0050, OP_CRON, OP_GR_S, NULL, ARG_NONE, OP_FL_OS | OP_FL_MX16 },
	{ 0051, OP_NONE, OP_GR_NONE, NULL, ARG_UNKNOWN, OP_FL_NONE },
	{ 0052, OP_NONE, OP_GR_NONE, NULL, ARG_UNKNOWN, OP_FL_NONE },
	{ 0053, OP_NONE, OP_GR_NONE, NULL, ARG_UNKNOWN, OP_FL_NONE },
	{ 0054, OP_NONE, OP_GR_NONE, NULL, ARG_UNKNOWN, OP_FL_NONE },
	{ 0055, OP_NONE, OP_GR_NONE, NULL, ARG_UNKNOWN, OP_FL_NONE },
	{ 0056, OP_NONE, OP_GR_NONE, NULL, ARG_UNKNOWN, OP_FL_NONE },
	{ 0057, OP_NONE, OP_GR_NONE, NULL, ARG_UNKNOWN, OP_FL_NONE },

	{ 0060, OP_NONE, OP_GR_NONE, NULL, ARG_UNKNOWN, OP_FL_NONE },
	{ 0061, OP_NONE, OP_GR_NONE, NULL, ARG_UNKNOWN, OP_FL_NONE },
	{ 0062, OP_NONE, OP_GR_NONE, NULL, ARG_UNKNOWN, OP_FL_NONE },
	{ 0063, OP_NONE, OP_GR_NONE, NULL, ARG_UNKNOWN, OP_FL_NONE },
	{ 0064, OP_NONE, OP_GR_NONE, NULL, ARG_UNKNOWN, OP_FL_NONE },
	{ 0065, OP_NONE, OP_GR_NONE, NULL, ARG_UNKNOWN, OP_FL_NONE },
	{ 0066, OP_NONE, OP_GR_NONE, NULL, ARG_UNKNOWN, OP_FL_NONE },
	{ 0067, OP_NONE, OP_GR_NONE, NULL, ARG_UNKNOWN, OP_FL_NONE },

	{ 0070, OP_NONE, OP_GR_NONE, NULL, ARG_UNKNOWN, OP_FL_NONE },
	{ 0071, OP_NONE, OP_GR_NONE, NULL, ARG_UNKNOWN, OP_FL_NONE },
	{ 0072, OP_NONE, OP_GR_NONE, NULL, ARG_UNKNOWN, OP_FL_NONE },
	{ 0073, OP_NONE, OP_GR_NONE, NULL, ARG_UNKNOWN, OP_FL_NONE },
	{ 0074, OP_NONE, OP_GR_NONE, NULL, ARG_UNKNOWN, OP_FL_NONE },
	{ 0075, OP_NONE, OP_GR_NONE, NULL, ARG_UNKNOWN, OP_FL_NONE },
	{ 0076, OP_NONE, OP_GR_NONE, NULL, ARG_UNKNOWN, OP_FL_NONE },
	{ 0077, OP_NONE, OP_GR_NONE, NULL, ARG_UNKNOWN, OP_FL_NONE },

	{ 0100, OP_HLT, OP_GR_S, NULL, ARG_SHORT7, OP_FL_OS },
	{ 0101, OP_HLT, OP_GR_S, NULL, ARG_SHORT7, OP_FL_OS },
	{ 0102, OP_HLT, OP_GR_S, NULL, ARG_SHORT7, OP_FL_OS },
	{ 0103, OP_HLT, OP_GR_S, NULL, ARG_SHORT7, OP_FL_OS },
	{ 0104, OP_HLT, OP_GR_S, NULL, ARG_SHORT7, OP_FL_OS },
	{ 0105, OP_HLT, OP_GR_S, NULL, ARG_SHORT7, OP_FL_OS },
	{ 0106, OP_HLT, OP_GR_S, NULL, ARG_SHORT7, OP_FL_OS },
	{ 0107, OP_HLT, OP_GR_S, NULL, ARG_SHORT7, OP_FL_OS },

	{ 0110, OP_MCL, OP_GR_S, NULL, ARG_NONE, OP_FL_OS },
	{ 0111, OP_MCL, OP_GR_S, NULL, ARG_NONE, OP_FL_OS },
	{ 0112, OP_MCL, OP_GR_S, NULL, ARG_NONE, OP_FL_OS },
	{ 0113, OP_MCL, OP_GR_S, NULL, ARG_NONE, OP_FL_OS },
	{ 0114, OP_MCL, OP_GR_S, NULL, ARG_NONE, OP_FL_OS },
	{ 0115, OP_MCL, OP_GR_S, NULL, ARG_NONE, OP_FL_OS },
	{ 0116, OP_MCL, OP_GR_S, NULL, ARG_NONE, OP_FL_OS },
	{ 0117, OP_MCL, OP_GR_S, NULL, ARG_NONE, OP_FL_OS },

	{ 0120, OP_CIT, OP_GR_S, NULL, ARG_NONE, OP_FL_OS },
	{ 0121, OP_SIL, OP_GR_S, NULL, ARG_NONE, OP_FL_OS },
	{ 0122, OP_SIU, OP_GR_S, NULL, ARG_NONE, OP_FL_OS },
	{ 0123, OP_SIT, OP_GR_S, NULL, ARG_NONE, OP_FL_OS },
	{ 0124, OP_SIND, OP_GR_S, NULL, ARG_NONE, OP_FL_OS | OP_FL_MX16 },
	{ 0125, OP_NONE, OP_GR_NONE, NULL, ARG_UNKNOWN, OP_FL_NONE },
	{ 0126, OP_NONE, OP_GR_NONE, NULL, ARG_UNKNOWN, OP_FL_NONE },
	{ 0127, OP_NONE, OP_GR_NONE, NULL, ARG_UNKNOWN, OP_FL_NONE },

	{ 0130, OP_GIL, OP_GR_S, NULL, ARG_NONE, OP_FL_OS },
	{ 0131, OP_GIL, OP_GR_S, NULL, ARG_NONE, OP_FL_OS },
	{ 0132, OP_GIL, OP_GR_S, NULL, ARG_NONE, OP_FL_OS },
	{ 0133, OP_GIL, OP_GR_S, NULL, ARG_NONE, OP_FL_OS },
	{ 0134, OP_GIL, OP_GR_S, NULL, ARG_NONE, OP_FL_OS },
	{ 0135, OP_GIL, OP_GR_S, NULL, ARG_NONE, OP_FL_OS },
	{ 0136, OP_GIL, OP_GR_S, NULL, ARG_NONE, OP_FL_OS },
	{ 0137, OP_GIL, OP_GR_S, NULL, ARG_NONE, OP_FL_OS },

	{ 0141, OP_LIP, OP_GR_S, NULL, ARG_NONE, OP_FL_OS },
	{ 0140, OP_LIP, OP_GR_S, NULL, ARG_NONE, OP_FL_OS },
	{ 0142, OP_LIP, OP_GR_S, NULL, ARG_NONE, OP_FL_OS },
	{ 0143, OP_LIP, OP_GR_S, NULL, ARG_NONE, OP_FL_OS },
	{ 0145, OP_LIP, OP_GR_S, NULL, ARG_NONE, OP_FL_OS },
	{ 0144, OP_LIP, OP_GR_S, NULL, ARG_NONE, OP_FL_OS },
	{ 0146, OP_LIP, OP_GR_S, NULL, ARG_NONE, OP_FL_OS },
	{ 0147, OP_LIP, OP_GR_S, NULL, ARG_NONE, OP_FL_OS },

	{ 0150, OP_NONE, OP_GR_NONE, NULL, ARG_UNKNOWN, OP_FL_NONE },
	{ 0151, OP_NONE, OP_GR_NONE, NULL, ARG_UNKNOWN, OP_FL_NONE },
	{ 0152, OP_NONE, OP_GR_NONE, NULL, ARG_UNKNOWN, OP_FL_NONE },
	{ 0153, OP_NONE, OP_GR_NONE, NULL, ARG_UNKNOWN, OP_FL_NONE },
	{ 0154, OP_NONE, OP_GR_NONE, NULL, ARG_UNKNOWN, OP_FL_NONE },
	{ 0155, OP_NONE, OP_GR_NONE, NULL, ARG_UNKNOWN, OP_FL_NONE },
	{ 0156, OP_NONE, OP_GR_NONE, NULL, ARG_UNKNOWN, OP_FL_NONE },
	{ 0157, OP_NONE, OP_GR_NONE, NULL, ARG_UNKNOWN, OP_FL_NONE },

	{ 0160, OP_NONE, OP_GR_NONE, NULL, ARG_UNKNOWN, OP_FL_NONE },
	{ 0161, OP_NONE, OP_GR_NONE, NULL, ARG_UNKNOWN, OP_FL_NONE },
	{ 0162, OP_NONE, OP_GR_NONE, NULL, ARG_UNKNOWN, OP_FL_NONE },
	{ 0163, OP_NONE, OP_GR_NONE, NULL, ARG_UNKNOWN, OP_FL_NONE },
	{ 0164, OP_NONE, OP_GR_NONE, NULL, ARG_UNKNOWN, OP_FL_NONE },
	{ 0165, OP_NONE, OP_GR_NONE, NULL, ARG_UNKNOWN, OP_FL_NONE },
	{ 0166, OP_NONE, OP_GR_NONE, NULL, ARG_UNKNOWN, OP_FL_NONE },
	{ 0167, OP_NONE, OP_GR_NONE, NULL, ARG_UNKNOWN, OP_FL_NONE },

	{ 0170, OP_NONE, OP_GR_NONE, NULL, ARG_UNKNOWN, OP_FL_NONE },
	{ 0171, OP_NONE, OP_GR_NONE, NULL, ARG_UNKNOWN, OP_FL_NONE },
	{ 0172, OP_NONE, OP_GR_NONE, NULL, ARG_UNKNOWN, OP_FL_NONE },
	{ 0173, OP_NONE, OP_GR_NONE, NULL, ARG_UNKNOWN, OP_FL_NONE },
	{ 0174, OP_NONE, OP_GR_NONE, NULL, ARG_UNKNOWN, OP_FL_NONE },
	{ 0175, OP_NONE, OP_GR_NONE, NULL, ARG_UNKNOWN, OP_FL_NONE },
	{ 0176, OP_NONE, OP_GR_NONE, NULL, ARG_UNKNOWN, OP_FL_NONE },
	{ 0177, OP_NONE, OP_GR_NONE, NULL, ARG_UNKNOWN, OP_FL_NONE }

};

static const struct opdef iset_74[] = {
	{ 0, OP_UJ, OP_GR_J, NULL, ARG_NORM | ARG_A_JUMP, OP_FL_NONE },
	{ 1, OP_JL, OP_GR_J, NULL, ARG_NORM | ARG_A_JUMP, OP_FL_NONE },
	{ 2, OP_JE, OP_GR_J, NULL, ARG_NORM | ARG_A_JUMP, OP_FL_NONE },
	{ 3, OP_JG, OP_GR_J, NULL, ARG_NORM | ARG_A_JUMP, OP_FL_NONE },
	{ 4, OP_JZ, OP_GR_J, NULL, ARG_NORM | ARG_A_JUMP, OP_FL_NONE },
	{ 5, OP_JM, OP_GR_J, NULL, ARG_NORM | ARG_A_JUMP, OP_FL_NONE },
	{ 6, OP_JN, OP_GR_J, NULL, ARG_NORM | ARG_A_JUMP, OP_FL_NONE },
	{ 7, OP_LJ, OP_GR_J, NULL, ARG_NORM | ARG_A_JUMP, OP_FL_NONE }
};

static const struct opdef iset_75[] = {
	{ 0, OP_LD, OP_GR_L, NULL, ARG_NORM | ARG_A_WORD, OP_FL_NONE },
	{ 1, OP_LF, OP_GR_L, NULL, ARG_NORM | ARG_A_WORD, OP_FL_NONE },
	{ 2, OP_LA, OP_GR_L, NULL, ARG_NORM | ARG_A_WORD, OP_FL_NONE },
	{ 3, OP_LL, OP_GR_L, NULL, ARG_NORM | ARG_A_WORD, OP_FL_NONE },
	{ 4, OP_TD, OP_GR_L, NULL, ARG_NORM | ARG_A_WORD, OP_FL_NONE },
	{ 5, OP_TF, OP_GR_L, NULL, ARG_NORM | ARG_A_WORD, OP_FL_NONE },
	{ 6, OP_TA, OP_GR_L, NULL, ARG_NORM | ARG_A_WORD, OP_FL_NONE },
	{ 7, OP_TL, OP_GR_L, NULL, ARG_NORM | ARG_A_WORD, OP_FL_NONE }
};

static const struct opdef iset_76[] = {
	{ 0, OP_RD, OP_GR_G, NULL, ARG_NORM | ARG_A_WORD, OP_FL_NONE },
	{ 1, OP_RF, OP_GR_G, NULL, ARG_NORM | ARG_A_WORD, OP_FL_NONE },
	{ 2, OP_RA, OP_GR_G, NULL, ARG_NORM | ARG_A_WORD, OP_FL_NONE },
	{ 3, OP_RL, OP_GR_G, NULL, ARG_NORM | ARG_A_WORD, OP_FL_NONE },
	{ 4, OP_PD, OP_GR_G, NULL, ARG_NORM | ARG_A_WORD, OP_FL_NONE },
	{ 5, OP_PF, OP_GR_G, NULL, ARG_NORM | ARG_A_WORD, OP_FL_NONE },
	{ 6, OP_PA, OP_GR_G, NULL, ARG_NORM | ARG_A_WORD, OP_FL_NONE },
	{ 7, OP_PL, OP_GR_G, NULL, ARG_NORM | ARG_A_WORD, OP_FL_NONE }
};

static const struct opdef iset_77[] = {
	{ 0, OP_MB, OP_GR_BN, NULL, ARG_NORM | ARG_A_WORD, OP_FL_OS },
	{ 1, OP_IM, OP_GR_BN, NULL, ARG_NORM | ARG_A_WORD, OP_FL_OS },
	{ 2, OP_KI, OP_GR_BN, NULL, ARG_NORM | ARG_A_WORD, OP_FL_OS },
	{ 3, OP_FI, OP_GR_BN, NULL, ARG_NORM | ARG_A_WORD, OP_FL_OS },
	{ 4, OP_SP, OP_GR_BN, NULL, ARG_NORM | ARG_A_WORD, OP_FL_OS },
	{ 5, OP_MD, OP_GR_BN, NULL, ARG_NORM, OP_FL_NONE },
	{ 6, OP_RZ, OP_GR_BN, NULL, ARG_NORM | ARG_A_WORD, OP_FL_NONE },
	{ 7, OP_IB, OP_GR_BN, NULL, ARG_NORM | ARG_A_WORD, OP_FL_NONE }
};

// -----------------------------------------------------------------------
const struct opdef * emdas_get_op(uint16_t opcode)
{
	const struct opdef *opdef = iset + _OP(opcode);
	if (!opdef->extop_fun) {
		return opdef;
	} else {
		return opdef->extop_fun(opcode);
	}
}

// -----------------------------------------------------------------------
static const struct opdef * get_extop_37(uint16_t opcode)
{
	return iset_37 + _A(opcode);
}

// -----------------------------------------------------------------------
static const struct opdef * get_extop_70(uint16_t opcode)
{
	return iset_70 + _A(opcode);
}

// -----------------------------------------------------------------------
static const struct opdef * get_extop_71(uint16_t opcode)
{
	return iset_71 + ((opcode & 0b0000001100000000) >> 8);
}

// -----------------------------------------------------------------------
static const struct opdef * get_extop_72(uint16_t opcode)
{
	return iset_72 + (((opcode & 0b0000001000000000) >> 3) | (opcode & 0b0000000000111111));
}

// -----------------------------------------------------------------------
static const struct opdef * get_extop_73(uint16_t opcode)
{
	return iset_73 + (((opcode & 0b0000001111000000) >> 3) | (opcode & 0b0000000000000111));
}

// -----------------------------------------------------------------------
static const struct opdef * get_extop_74(uint16_t opcode)
{
	return iset_74 + _A(opcode);
}

// -----------------------------------------------------------------------
static const struct opdef * get_extop_75(uint16_t opcode)
{
	return iset_75 + _A(opcode);
}

// -----------------------------------------------------------------------
static const struct opdef * get_extop_76(uint16_t opcode)
{
	return iset_76 + _A(opcode);
}

// -----------------------------------------------------------------------
static const struct opdef * get_extop_77(uint16_t opcode)
{
	return iset_77 + _A(opcode);
}


// vim: tabstop=4 shiftwidth=4 autoindent
